[[data]]
id = 1
locationLong = 12.12
locationLat = 3.53
location = "Muglin"
districtId = 35
highwayIds = [1, 2] 

  [[data.status]]
  time = 2024-10-23T00:00:00Z
  condition = "some issue in bride"
  conditionNep = "पुलमा समस्या"
  code = "CLOSED"

  [[data.status]]
  time = 2024-10-24T00:00:00Z
  condition = "bridge one way"
  conditionNep = "पुलमा समस्या, एकतर्फी बाटो"
  code = "ONE_WAY"

  [[data.status]]
  time = 2024-10-25T00:00:00Z
  condition = "fixed"
  conditionNep = "पुल पुरा रुपमा सुचारु "
  code = "OPEN"
